name: test_app
description: A test Flutter app

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/data/sample.json
    - lib/
    - lib/gen/
    - lib/generated/
