use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

#[derive(Debug, Deserialize, Serialize)]
struct PubspecYaml {
    name: String,
    #[serde(default)]
    flutter: FlutterSection,
}

#[derive(Debug, Deserialize, Serialize)]
struct FlutterSection {
    #[serde(default)]
    assets: Vec<String>,
}

impl Default for FlutterSection {
    fn default() -> Self {
        Self {
            assets: Vec::new(),
        }
    }
}

pub fn generate_assets() {
    generate_assets_from_path("test_flutter_app")
}

pub fn generate_assets_from_path(project_path: &str) {
    println!("Generating assets from {}", project_path);
    
    // pubspec.yamlを読み込み
    let pubspec_path = format!("{}/pubspec.yaml", project_path);
    let pubspec_content = match fs::read_to_string(&pubspec_path) {
        Ok(content) => content,
        Err(e) => {
            eprintln!("Error reading {}: {}", pubspec_path, e);
            return;
        }
    };
    
    // YAMLを解析
    let pubspec: PubspecYaml = match serde_yaml::from_str(&pubspec_content) {
        Ok(pubspec) => pubspec,
        Err(e) => {
            eprintln!("Error parsing pubspec.yaml: {}", e);
            return;
        }
    };
    
    // アセットファイルを収集
    let asset_files = collect_asset_files_from_project(&pubspec.flutter.assets, project_path);
    
    // Dartクラスを生成
    let dart_code = generate_dart_assets_class(&asset_files);
    
    // 出力ディレクトリを作成
    let output_dir = format!("{}/lib/gen", project_path);
    let output_path = Path::new(&output_dir);
    if let Err(e) = fs::create_dir_all(output_path) {
        eprintln!("Error creating output directory: {}", e);
        return;
    }
    
    // ファイルに書き込み
    let output_file_path = format!("{}/assets.gen.dart", output_dir);
    if let Err(e) = fs::write(&output_file_path, dart_code) {
        eprintln!("Error writing assets.gen.dart: {}", e);
        return;
    }
    
    println!("Generated assets.gen.dart with {} asset constants", asset_files.len());
}

fn collect_asset_files_from_project(asset_paths: &[String], project_path: &str) -> Vec<String> {
    let mut asset_files = Vec::new();
    
    for path in asset_paths {
        let full_path = format!("{}/{}", project_path, path);
        let path_buf = PathBuf::from(&full_path);
        
        if path_buf.is_file() {
            // 単一ファイルの場合
            asset_files.push(path.to_string());
        } else if path_buf.is_dir() {
            // ディレクトリの場合、再帰的に検索
            for entry in WalkDir::new(&path_buf).into_iter().filter_map(|e| e.ok()) {
                if entry.file_type().is_file() {
                    if let Some(relative_path) = entry.path().strip_prefix(&path_buf).ok() {
                        let asset_path = format!("{}/{}", path, relative_path.to_string_lossy());
                        asset_files.push(asset_path);
                    }
                }
            }
        }
    }
    
    asset_files.sort();
    asset_files
}

fn generate_dart_assets_class(asset_files: &[String]) -> String {
    let mut dart_code = String::new();
    
    // クラスヘッダー
    dart_code.push_str("// This file is auto-generated. Do not edit.\n");
    dart_code.push_str("// Generated by SuperFastGen\n\n");
    dart_code.push_str("class Assets {\n");
    
    // アセット定数を生成
    for asset_file in asset_files {
        let constant_name = asset_file_to_constant_name(asset_file);
        dart_code.push_str(&format!("  static const String {} = '{}';\n", constant_name, asset_file));
    }
    
    // クラス終了
    dart_code.push_str("}\n");
    
    dart_code
}

fn asset_file_to_constant_name(asset_file: &str) -> String {
    // ファイルパスを定数名に変換
    // 例: "assets/images/logo.png" -> "assetsImagesLogoPng"
    let mut constant_name = String::new();
    
    for part in asset_file.split('/') {
        if !part.is_empty() {
            // 最初の文字を大文字に
            if let Some(first_char) = part.chars().next() {
                constant_name.push(first_char.to_uppercase().next().unwrap());
                constant_name.push_str(&part[1..]);
            }
        }
    }
    
    // 特殊文字を除去
    constant_name = constant_name.replace(['.', '-', '_'], "");
    
    constant_name
}

pub fn process_images() {
    println!("Processing images...");
}

pub fn process_fonts() {
    println!("Processing fonts...");
} 

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;
    use std::fs;

    #[test]
    fn test_collect_asset_files_from_project() {
        // テスト用の一時ディレクトリを作成
        let temp_dir = TempDir::new().unwrap();
        let project_path = temp_dir.path();
        
        // アセットディレクトリを作成
        let assets_dir = project_path.join("assets");
        let images_dir = assets_dir.join("images");
        fs::create_dir_all(&images_dir).unwrap();
        
        // テストファイルを作成
        fs::write(images_dir.join("logo.png"), "fake image").unwrap();
        fs::write(assets_dir.join("data.json"), "fake data").unwrap();
        
        let asset_paths = vec![
            "assets/images/".to_string(),
            "assets/data.json".to_string(),
        ];
        
        let asset_files = collect_asset_files_from_project(&asset_paths, project_path.to_str().unwrap());
        
        assert_eq!(asset_files.len(), 2);
        assert!(asset_files.contains(&"assets/images/logo.png".to_string()));
        assert!(asset_files.contains(&"assets/data.json".to_string()));
    }

    #[test]
    fn test_generate_dart_assets_class() {
        let asset_files = vec![
            "assets/images/logo.png".to_string(),
            "assets/data/sample.json".to_string(),
        ];
        
        let dart_code = generate_dart_assets_class(&asset_files);
        
        assert!(dart_code.contains("class Assets"));
        assert!(dart_code.contains("AssetsImagesLogopng"));
        assert!(dart_code.contains("assets/images/logo.png"));
        assert!(dart_code.contains("AssetsDataSamplejson"));
        assert!(dart_code.contains("assets/data/sample.json"));
    }

    #[test]
    fn test_asset_file_to_constant_name() {
        let test_cases = vec![
            ("assets/images/logo.png", "AssetsImagesLogopng"),
            ("assets/data/sample.json", "AssetsDataSamplejson"),
            ("assets/fonts/Roboto-Regular.ttf", "AssetsFontsRobotoRegularttf"),
        ];
        
        for (input, expected) in test_cases {
            let result = asset_file_to_constant_name(input);
            assert_eq!(result, expected);
        }
    }

    #[test]
    fn test_parse_pubspec_yaml() {
        let yaml_content = r#"
name: test_app
flutter:
  assets:
    - assets/images/
    - assets/data/sample.json
"#;
        
        let pubspec: PubspecYaml = serde_yaml::from_str(yaml_content).unwrap();
        
        assert_eq!(pubspec.name, "test_app");
        assert_eq!(pubspec.flutter.assets.len(), 2);
        assert!(pubspec.flutter.assets.contains(&"assets/images/".to_string()));
        assert!(pubspec.flutter.assets.contains(&"assets/data/sample.json".to_string()));
    }

    #[test]
    fn test_parse_pubspec_yaml_without_assets() {
        let yaml_content = r#"
name: test_app
flutter:
"#;
        
        let pubspec: PubspecYaml = serde_yaml::from_str(yaml_content).unwrap();
        
        assert_eq!(pubspec.name, "test_app");
        assert_eq!(pubspec.flutter.assets.len(), 0);
    }
} 